spring:
  docker:
    compose:
      enabled: false
  profiles:
    active: secret
    include:
      - secret
  application:
    name: purin_bank
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require
    username: postgres.mxbexoylgfgijwgmviiq
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      data-source-properties:
        prepareThreshold: 0

    jpa:
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          jdbc:
            lob:
              non_contextual_creation: true
      show-sql: false

crypto:
  secret-key: ${crypto.secret-key}